language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
    - chmod +x ./gradlew
    - gem install ./bin/yoox-calabash-0.9.4.gem
    - npm install awsdevicefarmcli
after_script:
    - jarsigner -verify -verbose ./app/build/outputs/apk/app-debug.apk
    - yoox-calabash  -l
    - yoox-calabash -c -i '{"platform":"android","config":[{"iso":"IT","api":"Production","tests":["t4"]}]}'
    - zip tests.zip ./features/*
    - node ./node_modules/awsdevicefarmcli/scheduleRun.js --AWSAccessKeyId ${AWSAccessKeyId} --AWSSecretAccessKey ${AWSSecretAccessKey} --AWSRegion us-west-2 --AppApk ./app/build/outputs/apk/app-debug.apk --TestsZip ./tests.zip
# Let's try to build...
script: ./gradlew clean assembleDebug