language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
    - chmod +x ./gradlew
after_script:
    - jarsigner -verify -verbose ./app/build/outputs/apk/app-debug.apk
	- wget http://www.yoox.com
# Let's try to build...
script: ./gradlew clean assembleDebug