language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
    - chmod +x ./gradlew
    - chmod +x ./bin/devicefarm/application.py
    - gem install ./bin/yoox-calabash-0.9.4.gem
    - sudo pip install boto3
after_script:
    - jarsigner -verify -verbose ./app/build/outputs/apk/app-debug.apk
    - yoox-calabash  -l
    - yoox-calabash -c -i '{"platform":"android","config":[{"iso":"IT","api":"Production","tests":["t4"]}]}'
    - zip tests.zip ./features/*
    - sudo ./bin/devicefarm/application.py android tests.zip ./app/build/outputs/apk/app-debug.apk
# Let's try to build...
script: ./gradlew clean assembleDebug